---
- block:
  - name: CHECKING FOR EPEL REPO
    stat:
      path: /etc/yum.repos.d/epel.repo
    register: epel_result

  - name: INSTALL EPEL REPO
    package:
      name: epel-release
      state: present
    when: epel_result.stat.exists == False

  - name: INSTALL REMI REPO
    yum:
      name: "http://rpms.remirepo.net/enterprise/remi-release-7.rpm"
      state: present

  - name: IMPORT REMI GPG KEY.
    rpm_key:
      key: "http://rpms.remirepo.net/RPM-GPG-KEY-remi"
      state: present

  - name: UPGRADE ALL PACKAGES
    yum:
      name: '*'
      state: latest
  become: true